// const currencies = [
//     { id: 1, country: 'United States', currency: 'USD' },
//     { id: 2, country: 'Eurozone', currency: 'EUR' },
//     { id: 3, country: 'Japan', currency: 'JPY' },
//     { id: 4, country: 'United Kingdom', currency: 'GBP' },
//     { id: 5, country: 'Switzerland', currency: 'CHF' },
//     { id: 6, country: 'Canada', currency: 'CAD' },
//     { id: 7, country: 'Australia', currency: 'AUD' },
//     { id: 8, country: 'New Zealand', currency: 'NZD' },
//     { id: 9, country: 'China', currency: 'CNY' },
//     { id: 10, country: 'India', currency: 'INR' },
//     { id: 11, country: 'Brazil', currency: 'BRL' },
//     { id: 12, country: 'Russia', currency: 'RUB' },
//     { id: 13, country: 'South Africa', currency: 'ZAR' },
//     { id: 14, country: 'Singapore', currency: 'SGD' },
//     { id: 15, country: 'Sweden', currency: 'SEK' },
//     { id: 16, country: 'Norway', currency: 'NOK' },
//     { id: 17, country: 'Denmark', currency: 'DKK' },
//     { id: 18, country: 'Mexico', currency: 'MXN' },
//     { id: 19, country: 'Hong Kong', currency: 'HKD' },
//     { id: 20, country: 'South Korea', currency: 'KRW' },
//     { id: 21, country: 'Turkey', currency: 'TRY' },
//     { id: 22, country: 'Argentina', currency: 'ARS' },
//     { id: 23, country: 'Egypt', currency: 'EGP' },
//     { id: 24, country: 'Saudi Arabia', currency: 'SAR' },
//     { id: 25, country: 'United Arab Emirates', currency: 'AED' },
//     { id: 26, country: 'Israel', currency: 'ILS' },
//     { id: 27, country: 'Thailand', currency: 'THB' },
//     { id: 28, country: 'Malaysia', currency: 'MYR' },
//     { id: 29, country: 'Indonesia', currency: 'IDR' },
//     { id: 30, country: 'Philippines', currency: 'PHP' },
//     { id: 31, country: 'Pakistan', currency: 'PKR' },
//     { id: 32, country: 'Bangladesh', currency: 'BDT' },
//     { id: 33, country: 'Nigeria', currency: 'NGN' },
//     { id: 34, country: 'Russia', currency: 'RUB' },
//     { id: 35, country: 'Mexico', currency: 'MXN' },
//     { id: 36, country: 'Ethiopia', currency: 'ETB' },
//     { id: 37, country: 'Vietnam', currency: 'VND' },
//     { id: 38, country: 'Egypt', currency: 'EGP' },
//     { id: 39, country: 'Iran', currency: 'IRR' },
//     { id: 40, country: 'Turkey', currency: 'TRY' },
//     { id: 41, country: 'Afghanistan', currency: 'AFN' },
//     { id: 42, country: 'Albania', currency: 'ALL' },
//     { id: 43, country: 'Algeria', currency: 'DZD' },
//     { id: 44, country: 'Andorra', currency: 'EUR' },
//     { id: 45, country: 'Angola', currency: 'AOA' },
//     { id: 46, country: 'Antigua and Barbuda', currency: 'XCD' },
//     { id: 47, country: 'Argentina', currency: 'ARS' },
//     { id: 48, country: 'Armenia', currency: 'AMD' },
//     { id: 49, country: 'Austria', currency: 'EUR' },
//     { id: 50, country: 'Azerbaijan', currency: 'AZN' },
//     { id: 51, country: 'Bahamas', currency: 'BSD' },
//     { id: 52, country: 'Bahrain', currency: 'BHD' },
//     { id: 53, country: 'Bangladesh', currency: 'BDT' },
//     { id: 54, country: 'Barbados', currency: 'BBD' },
//     { id: 55, country: 'Belarus', currency: 'BYN' },
//     { id: 56, country: 'Belgium', currency: 'EUR' },
//     { id: 57, country: 'Belize', currency: 'BZD' },
//     { id: 58, country: 'Benin', currency: 'XOF' },
//     { id: 59, country: 'Bhutan', currency: 'BTN' },
//     { id: 60, country: 'Bolivia', currency: 'BOB' },
//     { id: 61, country: 'Bosnia and Herzegovina', currency: 'BAM' },
//     { id: 62, country: 'Botswana', currency: 'BWP' },
//     { id: 63, country: 'Brunei', currency: 'BND' },
//     { id: 64, country: 'Bulgaria', currency: 'BGN' },
//     { id: 65, country: 'Burkina Faso', currency: 'XOF' },
//     { id: 66, country: 'Burundi', currency: 'BIF' },
//     { id: 67, country: 'Cabo Verde', currency: 'CVE' },
//     { id: 68, country: 'Cambodia', currency: 'KHR' },
//     { id: 69, country: 'Cameroon', currency: 'XAF' },
//     { id: 70, country: 'Central African Republic', currency: 'XAF' },
//     { id: 71, country: 'Chad', currency: 'XAF' },
//     { id: 72, country: 'Chile', currency: 'CLP' },
//     { id: 73, country: 'Colombia', currency: 'COP' },
//     { id: 74, country: 'Comoros', currency: 'KMF' },
//     { id: 75, country: 'Costa Rica', currency: 'CRC' },
//     { id: 76, country: 'Croatia', currency: 'HRK' },
//     { id: 77, country: 'Cuba', currency: 'CUP' },
//     { id: 78, country: 'Cyprus', currency: 'EUR' },
//     { id: 79, country: 'Czech Republic', currency: 'CZK' },
//     { id: 80, country: 'Djibouti', currency: 'DJF' },
//     { id: 81, country: 'Dominican Republic', currency: 'DOP' },
//     { id: 82, country: 'Ecuador', currency: 'USD' },
//     { id: 83, country: 'El Salvador', currency: 'USD' },
//     { id: 84, country: 'Estonia', currency: 'EUR' },
//     { id: 85, country: 'Fiji', currency: 'FJD' },
//     { id: 86, country: 'Finland', currency: 'EUR' },
//     { id: 87, country: 'France', currency: 'EUR' },
//     { id: 88, country: 'Gambia', currency: 'GMD' },
//     { id: 89, country: 'Georgia', currency: 'GEL' },
//     { id: 90, country: 'Germany', currency: 'EUR' },
//     { id: 91, country: 'Ghana', currency: 'GHS' },
//     { id: 92, country: 'Greece', currency: 'EUR' },
//     { id: 93, country: 'Guatemala', currency: 'GTQ' },
//     { id: 94, country: 'Haiti', currency: 'HTG' },
//     { id: 95, country: 'Honduras', currency: 'HNL' },
//     { id: 96, country: 'Hungary', currency: 'HUF' },
//     { id: 97, country: 'Iceland', currency: 'ISK' },
//     { id: 98, country: 'Indonesia', currency: 'IDR' },
//     { id: 99, country: 'Iraq', currency: 'IQD' },
//     { id: 100, country: 'Ireland', currency: 'EUR' },
//     { id: 101, country: 'Italy', currency: 'EUR' },
//   { id: 102, country: 'Jamaica', currency: 'JMD' },
//   { id: 103, country: 'Latvia', currency: 'EUR' },
//   { id: 104, country: 'Lebanon', currency: 'LBP' },
//   { id: 105, country: 'Lithuania', currency: 'EUR' },
//   { id: 106, country: 'Luxembourg', currency: 'EUR' },
//   { id: 107, country: 'Maldives', currency: 'MVR' },
//   { id: 108, country: 'Malta', currency: 'EUR' },
//   { id: 109, country: 'Mauritius', currency: 'MUR' },
//   { id: 110, country: 'Moldova', currency: 'MDL' },
//   { id: 111, country: 'Monaco', currency: 'EUR' },
//   { id: 112, country: 'Mongolia', currency: 'MNT' },
//   { id: 113, country: 'Montenegro', currency: 'EUR' },
//   { id: 114, country: 'Morocco', currency: 'MAD' },
//   { id: 115, country: 'Nepal', currency: 'NPR' },
//   { id: 116, country: 'Netherlands', currency: 'EUR' },
//   { id: 117, country: 'New Zealand', currency: 'NZD' },
//   { id: 118, country: 'Nicaragua', currency: 'NIO' },
//   { id: 119, country: 'North Macedonia', currency: 'MKD' },
//   { id: 120, country: 'Norway', currency: 'NOK' },
//   { id: 121, country: 'Oman', currency: 'OMR' },
//   { id: 122, country: 'Panama', currency: 'PAB' },
//   { id: 123, country: 'Papua New Guinea', currency: 'PGK' },
//   { id: 124, country: 'Paraguay', currency: 'PYG' },
//   { id: 125, country: 'Peru', currency: 'PEN' },
//   { id: 126, country: 'Poland', currency: 'PLN' },
//   { id: 127, country: 'Portugal', currency: 'EUR' },
//   { id: 128, country: 'Qatar', currency: 'QAR' },
//   { id: 129, country: 'Romania', currency: 'RON' },
//   { id: 130, country: 'Russia', currency: 'RUB' },
//   { id: 131, country: 'Rwanda', currency: 'RWF' },
//   { id: 132, country: 'Saint Kitts and Nevis', currency: 'XCD' },
//   { id: 133, country: 'Saint Lucia', currency: 'XCD' },
//   { id: 134, country: 'Saint Vincent and the Grenadines', currency: 'XCD' },
//   { id: 135, country: 'Samoa', currency: 'WST' },
//   { id: 136, country: 'San Marino', currency: 'EUR' },
//   { id: 137, country: 'Sao Tome and Principe', currency: 'STN' },
//   { id: 138, country: 'Saudi Arabia', currency: 'SAR' },
//   { id: 139, country: 'Senegal', currency: 'XOF' },
//   { id: 140, country: 'Serbia', currency: 'RSD' },
//   { id: 141, country: 'Seychelles', currency: 'SCR' },
//   { id: 142, country: 'Sierra Leone', currency: 'SLL' },
//   { id: 143, country: 'Singapore', currency: 'SGD' },
//   { id: 144, country: 'Slovakia', currency: 'EUR' },
//   { id: 145, country: 'Slovenia', currency: 'EUR' },
//   { id: 146, country: 'Solomon Islands', currency: 'SBD' },
//   { id: 147, country: 'Somalia', currency: 'SOS' },
//   { id: 148, country: 'South Africa', currency: 'ZAR' },
//   { id: 149, country: 'South Sudan', currency: 'SSP' },
//   { id: 150, country: 'Spain', currency: 'EUR' },
//   { id: 151, country: 'Sri Lanka', currency: 'LKR' },
//   { id: 152, country: 'Sudan', currency: 'SDG' },
//   { id: 153, country: 'Suriname', currency: 'SRD' },
//   { id: 154, country: 'Sweden', currency: 'SEK' },
//   { id: 156, country: 'Syria', currency: 'SYP' },
//   { id: 157, country: 'Taiwan', currency: 'TWD' },
//   { id: 158, country: 'Tajikistan', currency: 'TJS' },
//   { id: 159, country: 'Tanzania', currency: 'TZS' },
//   { id: 160, country: 'Thailand', currency: 'THB' },
//   { id: 161, country: 'Tonga', currency: 'TOP' },
//   { id: 162, country: 'Trinidad and Tobago', currency: 'TTD' },
//   { id: 163, country: 'Tunisia', currency: 'TND' },
//   { id: 164, country: 'Turkey', currency: 'TRY' },
//   { id: 165, country: 'Turkmenistan', currency: 'TMT' },
//   { id: 166, country: 'Tuvalu', currency: 'TVD[G]' },
//   { id: 167, country: 'Uganda', currency: 'UGX' },
//   { id: 168, country: 'Ukraine', currency: 'UAH' },
//   { id: 169, country: 'United Arab Emirates', currency: 'AED' },
//   { id: 172, country: 'Uruguay', currency: 'UYU' },
//   { id: 173, country: 'Uzbekistan', currency: 'UZS' },
//   { id: 174, country: 'Vanuatu', currency: 'VUV' },
//   { id: 175, country: 'Vatican City (Holy See)', currency: 'EUR' },
//   { id: 176, country: 'Venezuela', currency: 'VES' },
//   { id: 177, country: 'Vietnam', currency: 'VND' },
//   { id: 178, country: 'Yemen', currency: 'YER' },
//   { id: 179, country: 'Zambia', currency: 'ZMW' },
//   { id: 180, country: 'Zimbabwe', currency: 'ZWL' },
//   { id: 181, country: 'Togo', currency: 'XOF' },
//   { id: 182, country: 'Tonga', currency: 'TOP' },
//   { id: 183, country: 'Trinidad and Tobago', currency: 'TTD' },
//   { id: 184, country: 'Tunisia', currency: 'TND' },
//   { id: 185, country: 'Turkey', currency: 'TRY' },
//   { id: 186, country: 'Turkmenistan', currency: 'TMT' },
//   { id: 187, country: 'Tuvalu', currency: 'TVD[G]' },
//   { id: 188, country: 'Uganda', currency: 'UGX' },
//   { id: 189, country: 'Ukraine', currency: 'UAH' },
//   { id: 190, country: 'United Arab Emirates', currency: 'AED' },
//   { id: 193, country: 'Uruguay', currency: 'UYU' },
//   { id: 194, country: 'Uzbekistan', currency: 'UZS' },
//   { id: 195, country: 'Vanuatu', currency: 'VUV' },
//   { id: 196, country: 'Vatican City (Holy See)', currency: 'EUR' },
//   { id: 197, country: 'Venezuela', currency: 'VES' },
//   { id: 198, country: 'Vietnam', currency: 'VND' },
//   { id: 199, country: 'Yemen', currency: 'YER' },
//   { id: 200, country: 'Zambia', currency: 'ZMW' },
//   { id: 201, country: 'Zimbabwe', currency: 'ZWL' },
//   ];

const currencies = [
  { id: 1, country: "United States", currency: "USD", symbol: "$" },
  { id: 2, country: "Eurozone", currency: "EUR", symbol: "€" },
  { id: 3, country: "Japan", currency: "JPY", symbol: "¥" },
  { id: 4, country: "United Kingdom", currency: "GBP", symbol: "£" },
  { id: 5, country: "Switzerland", currency: "CHF", symbol: "CHF" },
  { id: 6, country: "Canada", currency: "CAD", symbol: "$" },
  { id: 7, country: "Australia", currency: "AUD", symbol: "$" },
  { id: 8, country: "New Zealand", currency: "NZD", symbol: "$" },
  { id: 9, country: "China", currency: "CNY", symbol: "¥" },
  { id: 10, country: "India", currency: "INR", symbol: "₹" },
  { id: 11, country: "Brazil", currency: "BRL", symbol: "R$" },
  { id: 12, country: "Russia", currency: "RUB", symbol: "₽" },
  { id: 13, country: "South Africa", currency: "ZAR", symbol: "R" },
  { id: 14, country: "Singapore", currency: "SGD", symbol: "$" },
  { id: 15, country: "Sweden", currency: "SEK", symbol: "kr" },
  { id: 16, country: "Norway", currency: "NOK", symbol: "kr" },
  { id: 17, country: "Denmark", currency: "DKK", symbol: "kr" },
  { id: 18, country: "Mexico", currency: "MXN", symbol: "$" },
  { id: 19, country: "Hong Kong", currency: "HKD", symbol: "$" },
  { id: 20, country: "South Korea", currency: "KRW", symbol: "₩" },
  { id: 21, country: "Turkey", currency: "TRY", symbol: "₺" },
  { id: 22, country: "Argentina", currency: "ARS", symbol: "$" },
  { id: 23, country: "Egypt", currency: "EGP", symbol: "£" },
  { id: 24, country: "Saudi Arabia", currency: "SAR", symbol: "﷼" },
  { id: 25, country: "United Arab Emirates", currency: "AED", symbol: "د.إ" },
  { id: 26, country: "Israel", currency: "ILS", symbol: "₪" },
  { id: 27, country: "Thailand", currency: "THB", symbol: "฿" },
  { id: 28, country: "Malaysia", currency: "MYR", symbol: "RM" },
  { id: 29, country: "Indonesia", currency: "IDR", symbol: "Rp" },
  { id: 30, country: "Philippines", currency: "PHP", symbol: "₱" },
  { id: 31, country: "Pakistan", currency: "PKR", symbol: "₨" },
  { id: 32, country: "Bangladesh", currency: "BDT", symbol: "৳" },
  { id: 33, country: "Nigeria", currency: "NGN", symbol: "₦" },
  { id: 34, country: "Russia", currency: "RUB", symbol: "₽" },
  { id: 35, country: "Mexico", currency: "MXN", symbol: "$" },
  { id: 36, country: "Ethiopia", currency: "ETB", symbol: "Br" },
  { id: 37, country: "Vietnam", currency: "VND", symbol: "₫" },
  { id: 38, country: "Egypt", currency: "EGP", symbol: "£" },
  { id: 39, country: "Iran", currency: "IRR", symbol: "﷼" },
  { id: 40, country: "Turkey", currency: "TRY", symbol: "₺" },
  { id: 41, country: "Afghanistan", currency: "AFN", symbol: "؋" },
  { id: 42, country: "Albania", currency: "ALL", symbol: "Lek" },
  { id: 43, country: "Algeria", currency: "DZD", symbol: "دج" },
  { id: 44, country: "Andorra", currency: "EUR", symbol: "€" },
  { id: 45, country: "Angola", currency: "AOA", symbol: "Kz" },
  { id: 46, country: "Antigua and Barbuda", currency: "XCD", symbol: "$" },
  { id: 47, country: "Argentina", currency: "ARS", symbol: "$" },
  { id: 48, country: "Armenia", currency: "AMD", symbol: "֏" },
  { id: 49, country: "Austria", currency: "EUR", symbol: "€" },
  { id: 50, country: "Azerbaijan", currency: "AZN", symbol: "₼" },
  { id: 51, country: "Bahamas", currency: "BSD", symbol: "$" },
  { id: 52, country: "Bahrain", currency: "BHD", symbol: ".د.ب" },
  { id: 53, country: "Bangladesh", currency: "BDT", symbol: "৳" },
  { id: 54, country: "Barbados", currency: "BBD", symbol: "$" },
  { id: 55, country: "Belarus", currency: "BYN", symbol: "Br" },
  { id: 56, country: "Belgium", currency: "EUR", symbol: "€" },
  { id: 57, country: "Belize", currency: "BZD", symbol: "BZ$" },
  { id: 58, country: "Benin", currency: "XOF", symbol: "CFA" },
  { id: 59, country: "Bhutan", currency: "BTN", symbol: "Nu." },
  { id: 60, country: "Bolivia", currency: "BOB", symbol: "Bs." },
  { id: 61, country: "Bosnia and Herzegovina", currency: "BAM", symbol: "KM" },
  { id: 62, country: "Botswana", currency: "BWP", symbol: "P" },
  { id: 63, country: "Brunei", currency: "BND", symbol: "$" },
  { id: 64, country: "Bulgaria", currency: "BGN", symbol: "лв" },
  { id: 65, country: "Burkina Faso", currency: "XOF", symbol: "CFA" },
  { id: 66, country: "Burundi", currency: "BIF", symbol: "FBu" },
  { id: 67, country: "Cabo Verde", currency: "CVE", symbol: "Esc" },
  { id: 68, country: "Cambodia", currency: "KHR", symbol: "៛" },
  { id: 69, country: "Cameroon", currency: "XAF", symbol: "FCFA" },
  {
    id: 70,
    country: "Central African Republic",
    currency: "XAF",
    symbol: "FCFA",
  },

  { id: 71, country: "Chad", currency: "XAF", symbol: "FCFA" },
  { id: 72, country: "Chile", currency: "CLP", symbol: "$" },
  { id: 73, country: "Colombia", currency: "COP", symbol: "$" },
  { id: 74, country: "Comoros", currency: "KMF", symbol: "CF" },
  { id: 75, country: "Costa Rica", currency: "CRC", symbol: "₡" },
  { id: 76, country: "Croatia", currency: "HRK", symbol: "kn" },
  { id: 77, country: "Cuba", currency: "CUP", symbol: "₱" },
  { id: 78, country: "Cyprus", currency: "EUR", symbol: "€" },
  { id: 79, country: "Czech Republic", currency: "CZK", symbol: "Kč" },
  { id: 80, country: "Djibouti", currency: "DJF", symbol: "Fdj" },
  { id: 81, country: "Dominican Republic", currency: "DOP", symbol: "RD$" },
  { id: 82, country: "Ecuador", currency: "USD", symbol: "$" },
  { id: 83, country: "El Salvador", currency: "USD", symbol: "$" },
  { id: 84, country: "Estonia", currency: "EUR", symbol: "€" },
  { id: 85, country: "Fiji", currency: "FJD", symbol: "$" },
  { id: 86, country: "Finland", currency: "EUR", symbol: "€" },
  { id: 87, country: "France", currency: "EUR", symbol: "€" },
  { id: 88, country: "Gambia", currency: "GMD", symbol: "D" },
  { id: 89, country: "Georgia", currency: "GEL", symbol: "₾" },
  { id: 90, country: "Germany", currency: "EUR", symbol: "€" },
  { id: 91, country: "Ghana", currency: "GHS", symbol: "GH₵" },
  { id: 92, country: "Greece", currency: "EUR", symbol: "€" },
  { id: 93, country: "Guatemala", currency: "GTQ", symbol: "Q" },
  { id: 94, country: "Haiti", currency: "HTG", symbol: "G" },
  { id: 95, country: "Honduras", currency: "HNL", symbol: "L" },
  { id: 96, country: "Hungary", currency: "HUF", symbol: "Ft" },
  { id: 97, country: "Iceland", currency: "ISK", symbol: "kr" },
  { id: 98, country: "Indonesia", currency: "IDR", symbol: "Rp" },
  { id: 99, country: "Iraq", currency: "IQD", symbol: "ع.د" },
  { id: 100, country: "Ireland", currency: "EUR", symbol: "€" },
  { id: 101, country: "Italy", currency: "EUR", symbol: "€" },
  { id: 102, country: "Jamaica", currency: "JMD", symbol: "J$" },
  { id: 103, country: "Latvia", currency: "EUR", symbol: "€" },
  { id: 104, country: "Lebanon", currency: "LBP", symbol: "ل.ل" },
  { id: 105, country: "Lithuania", currency: "EUR", symbol: "€" },
  { id: 106, country: "Luxembourg", currency: "EUR", symbol: "€" },
  { id: 107, country: "Maldives", currency: "MVR", symbol: ".ރ" },
  { id: 108, country: "Malta", currency: "EUR", symbol: "€" },
  { id: 109, country: "Mauritius", currency: "MUR", symbol: "₨" },
  { id: 110, country: "Moldova", currency: "MDL", symbol: "L" },
  { id: 111, country: "Monaco", currency: "EUR", symbol: "€" },
  { id: 112, country: "Mongolia", currency: "MNT", symbol: "₮" },
  { id: 113, country: "Montenegro", currency: "EUR", symbol: "€" },
  { id: 114, country: "Morocco", currency: "MAD", symbol: "د.م." },
  { id: 115, country: "Nepal", currency: "NPR", symbol: "₨" },
  { id: 116, country: "Netherlands", currency: "EUR", symbol: "€" },
  { id: 117, country: "New Zealand", currency: "NZD", symbol: "$" },
  { id: 118, country: "Nicaragua", currency: "NIO", symbol: "C$" },
  { id: 119, country: "North Macedonia", currency: "MKD", symbol: "ден" },
  { id: 120, country: "Norway", currency: "NOK", symbol: "kr" },
  { id: 121, country: "Oman", currency: "OMR", symbol: "ر.ع." },
  { id: 122, country: "Panama", currency: "PAB", symbol: "B/." },
  { id: 123, country: "Papua New Guinea", currency: "PGK", symbol: "K" },
  { id: 124, country: "Paraguay", currency: "PYG", symbol: "₲" },
  { id: 125, country: "Peru", currency: "PEN", symbol: "S/." },
  { id: 126, country: "Poland", currency: "PLN", symbol: "zł" },
  { id: 127, country: "Portugal", currency: "EUR", symbol: "€" },
  { id: 128, country: "Qatar", currency: "QAR", symbol: "ر.ق" },
  { id: 129, country: "Romania", currency: "RON", symbol: "lei" },
  { id: 130, country: "Russia", currency: "RUB", symbol: "₽" },
  { id: 131, country: "Rwanda", currency: "RWF", symbol: "FRw" },
  { id: 132, country: "Saint Kitts and Nevis", currency: "XCD", symbol: "$" },
  { id: 133, country: "Saint Lucia", currency: "XCD", symbol: "$" },
  {
    id: 134,
    country: "Saint Vincent and the Grenadines",
    currency: "XCD",
    symbol: "$",
  },
  { id: 135, country: "Samoa", currency: "WST", symbol: "WS$" },
  { id: 136, country: "San Marino", currency: "EUR", symbol: "€" },
  { id: 137, country: "Sao Tome and Principe", currency: "STN", symbol: "Db" },
  { id: 138, country: "Saudi Arabia", currency: "SAR", symbol: "ر.س" },
  { id: 139, country: "Senegal", currency: "XOF", symbol: "CFA" },
  { id: 140, country: "Serbia", currency: "RSD", symbol: "дин." },

  { id: 141, country: "Seychelles", currency: "SCR", symbol: "₨" },
  { id: 142, country: "Sierra Leone", currency: "SLL", symbol: "Le" },
  { id: 143, country: "Singapore", currency: "SGD", symbol: "$" },
  { id: 144, country: "Slovakia", currency: "EUR", symbol: "€" },
  { id: 145, country: "Slovenia", currency: "EUR", symbol: "€" },
  { id: 146, country: "Solomon Islands", currency: "SBD", symbol: "$" },
  { id: 147, country: "Somalia", currency: "SOS", symbol: "Sh" },
  { id: 148, country: "South Africa", currency: "ZAR", symbol: "R" },
  { id: 149, country: "South Sudan", currency: "SSP", symbol: "£" },
  { id: 150, country: "Spain", currency: "EUR", symbol: "€" },
  { id: 151, country: "Sri Lanka", currency: "LKR", symbol: "₨" },
  { id: 152, country: "Sudan", currency: "SDG", symbol: "£" },
  { id: 153, country: "Suriname", currency: "SRD", symbol: "$" },
  { id: 154, country: "Sweden", currency: "SEK", symbol: "kr" },
  { id: 156, country: "Syria", currency: "SYP", symbol: "£" },
  { id: 157, country: "Taiwan", currency: "TWD", symbol: "NT$" },
  { id: 158, country: "Tajikistan", currency: "TJS", symbol: "SM" },
  { id: 159, country: "Tanzania", currency: "TZS", symbol: "TSh" },
  { id: 160, country: "Thailand", currency: "THB", symbol: "฿" },
  { id: 161, country: "Tonga", currency: "TOP", symbol: "T$" },
  { id: 162, country: "Trinidad and Tobago", currency: "TTD", symbol: "TT$" },
  { id: 163, country: "Tunisia", currency: "TND", symbol: "د.ت" },
  { id: 164, country: "Turkey", currency: "TRY", symbol: "₺" },
  { id: 165, country: "Turkmenistan", currency: "TMT", symbol: "T" },
  { id: 166, country: "Tuvalu", currency: "TVD[G]", symbol: "$" },
  { id: 167, country: "Uganda", currency: "UGX", symbol: "USh" },
  { id: 168, country: "Ukraine", currency: "UAH", symbol: "₴" },
  { id: 169, country: "United Arab Emirates", currency: "AED", symbol: "د.إ" },
  { id: 172, country: "Uruguay", currency: "UYU", symbol: "$U" },
  { id: 173, country: "Uzbekistan", currency: "UZS", symbol: "лв" },
  { id: 174, country: "Vanuatu", currency: "VUV", symbol: "VT" },
  { id: 175, country: "Vatican City (Holy See)", currency: "EUR", symbol: "€" },
  { id: 176, country: "Venezuela", currency: "VES", symbol: "Bs." },
  { id: 177, country: "Vietnam", currency: "VND", symbol: "₫" },
  { id: 178, country: "Yemen", currency: "YER", symbol: "﷼" },
  { id: 179, country: "Zambia", currency: "ZMW", symbol: "ZK" },
  { id: 180, country: "Zimbabwe", currency: "ZWL", symbol: "$" },
  { id: 181, country: "Togo", currency: "XOF", symbol: "CFA" },
  { id: 182, country: "Tonga", currency: "TOP", symbol: "T$" },
  { id: 183, country: "Trinidad and Tobago", currency: "TTD", symbol: "TT$" },
  { id: 184, country: "Tunisia", currency: "TND", symbol: "د.ت" },
  { id: 185, country: "Turkey", currency: "TRY", symbol: "₺" },
  { id: 186, country: "Turkmenistan", currency: "TMT", symbol: "T" },
  { id: 187, country: "Tuvalu", currency: "TVD[G]", symbol: "$" },
  { id: 188, country: "Uganda", currency: "UGX", symbol: "USh" },
  { id: 189, country: "Ukraine", currency: "UAH", symbol: "₴" },
  { id: 190, country: "United Arab Emirates", currency: "AED", symbol: "د.إ" },
  { id: 193, country: "Uruguay", currency: "UYU", symbol: "$U" },
  { id: 194, country: "Uzbekistan", currency: "UZS", symbol: "лв" },
  { id: 195, country: "Vanuatu", currency: "VUV", symbol: "VT" },
  { id: 196, country: "Vatican City (Holy See)", currency: "EUR", symbol: "€" },
  { id: 197, country: "Venezuela", currency: "VES", symbol: "Bs." },
  { id: 198, country: "Vietnam", currency: "VND", symbol: "₫" },
  { id: 199, country: "Yemen", currency: "YER", symbol: "﷼" },
  { id: 200, country: "Zambia", currency: "ZMW", symbol: "ZK" },
  { id: 201, country: "Zimbabwe", currency: "ZWL", symbol: "$" },
];

// Create a Set to store unique country names
const uniqueCountries = new Set();

// Filter out duplicates and create a new array
const uniqueCurrencies = currencies.filter((currency) => {
  // If the country is not in the Set, add it and return true to keep the item
  if (!uniqueCountries.has(currency.country)) {
    uniqueCountries.add(currency.country);
    return true;
  }
  // If the country is already in the Set, return false to filter out the item
  return false;
});

const uniqueVal = [...uniqueCurrencies];

const sortedCurrency = uniqueVal
  .slice()
  .sort((a, b) =>
    a.country.toLowerCase().localeCompare(b.country.toLowerCase())
  );

export default sortedCurrency;
